language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository # required when using android support library
    - extra-google-m2repository # required when using play services
script:
  - ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
