language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository # required when using android support library
    - sys-img-armeabi-v7a-google_apis-25
before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
script:
  - ./gradlew build connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
