language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository # required when using android support library
# The ARM emulator is too slow to run the tests and fails with a timeout.
#    - sys-img-armeabi-v7a-google_apis-25
#before_script:
#  - android list targets
#  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a --tag google_apis
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
script:
#  - ./gradlew build connectedCheck
  - ./gradlew build
after_success:
  - bash <(curl -s https://codecov.io/bash)
